SELECT
    FDOC.DNUM AS id_ticket,
    FDOC.DFECHA AS fecha,
    FDOC.DBRUTO AS monto,
    FDOC.DIVA AS iva,
    (FDOC.DBRUTO + FDOC.DIVA) AS monto_con_iva,
    FDOC.DPAR1 AS vendedor,
    FCLI.CLNOM AS cliente,
    FAXINV.ICOD AS sku,
    FINV.IDESCR AS descrp,
    FAXINV.AICANT AS cantidad ,
    FAXINV.AIALMACEN AS almacen,
    FINV.ILISTA AS precio,
    FINV.IFAM3 AS  talla,
    FINV.IFAM4 AS color,
    FINV.IFAM5 AS temporada
FROM
    DOCUMENTOS FDOC
JOIN
    CLIENTES FCLI ON FDOC.CLICOD = FCLI.CLICOD
JOIN
    AUXILIAR_DE_INVENTARIOS FAXINV ON FDOC.DNUM = FAXINV.DREFER 
JOIN
    INVENTARIOS FINV ON FAXINV.ICOD = FINV.ICOD