SELECT
    FDOC.DNUM AS TicketNumber,
    FDOC.DFECHA AS Date,
    FDOC.DBRUTO AS AmountWithoutVAT,
    FDOC.DIVA AS VAT,
    (FDOC.DBRUTO + FDOC.DIVA) AS AmountWithVAT,
    FDOC.DPAR1 AS Seller,
    FCLI.CLNOM AS Client,
    FAXINV.ICOD AS SKU,
    FINV.IDESCR AS Description,
    FAXINV.AICANT AS Quantity,
    FAXINV.AIALMACEN AS Warehouse,
    FINV.ILISTA AS ListPrice,
    FINV.IFAM3 AS Size,
    FINV.IFAM4 AS Color,
    FINV.IFAM5 AS Season
FROM
    DOCUMENTOS FDOC
JOIN
    CLIENTES FCLI ON FDOC.CLICOD = FCLI.CLICOD
JOIN
    AUXILIAR_DE_INVENTARIOS FAXINV ON FDOC.DNUM = FAXINV.DREFER 
JOIN
    INVENTARIOS FINV ON FAXINV.ICOD = FINV.ICOD
WHERE
    FDOC.DTIPO = 'Sale'  
ORDER BY
    FDOC.DFECHA DESC;